using System.Collections.Generic;
using System.Text;
using GreenNide.ExpressionFilter;

namespace GreenNide.FilterGenerator.Generator;

public sealed partial class FilterGenerator
{
    // CodeGenerator.cs (partial class FilterGenerator)

    private static string GenerateCode(FilterClassDefinition def)
    {
        var genName = def.GeneratedClassName;

        var sb = new StringBuilder();
        // Шапка
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS8602, CS0108");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Linq;");

        // Добавляем using для namespace сущности, если он отличается от namespace фильтра
        var entityNamespace = def.EntityFullName != null
            ? def.EntityFullName.Substring(0, def.EntityFullName.LastIndexOf('.'))
            : null;
        if (!string.IsNullOrEmpty(entityNamespace) && entityNamespace != def.Namespace)
            sb.AppendLine($"using {entityNamespace};");

        sb.AppendLine();
        sb.AppendLine($"namespace {def.Namespace};");
        sb.AppendLine();

        // === Класс со свойствами ===
        sb.AppendLine($"public class {genName}");
        sb.AppendLine("{");

        // Свойства из Expression-полей
        foreach (var field in def.Fields)
            sb.AppendLine($"    public {field.PropertyTypeCs} {field.PropertyName} {{ get; set; }}");

        // Свойства из методов-предикатов
        var propSeen = new HashSet<string>();
        foreach (var method in def.Methods)
        foreach (var closure in method.ClosureProperties)
            if (propSeen.Add(closure.PropertyName))
                sb.AppendLine($"    public {closure.PropertyTypeCs} {closure.PropertyName} {{ get; set; }}");

        sb.AppendLine("}");
        sb.AppendLine();

        // === Extension класс ===
        sb.AppendLine($"public static class {genName}Extensions");
        sb.AppendLine("{");
        sb.AppendLine($"    public static IQueryable<{def.EntityName}> Apply(");
        sb.AppendLine($"        this IQueryable<{def.EntityName}> query,");
        sb.AppendLine($"        {genName} filter)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (filter is null) return query;");

        // Фильтры из Expression-полей
        foreach (var field in def.Fields)
            switch (field.Kind)
            {
                case FilterKind.Simple:
                    GenerateSimpleCondition(sb, field);
                    break;
                case FilterKind.Search:
                    GenerateSearchCondition(sb, field);
                    break;
            }

        // Методы-предикаты
        // Predicate-методы определены на классе Definition и принимают Definition-тип.
        // Генерируем промежуточный объект Definition, копируем closure-свойства и вызываем метод.
        if (def.Methods.Count > 0)
        {
            // Собираем уникальные closure-свойства из всех методов
            var allClosures = new HashSet<string>();
            foreach (var method in def.Methods)
            foreach (var closure in method.ClosureProperties)
                allClosures.Add(closure.PropertyName);

            sb.AppendLine($"        var __def = new {def.ClassName}();");
            foreach (var propName in allClosures)
                sb.AppendLine($"        __def.{propName} = filter.{propName};");
            sb.AppendLine();

            foreach (var method in def.Methods)
            {
                sb.AppendLine($"        var __pred_{method.MethodName} = {def.ClassName}.{method.MethodName}(__def);");
                sb.AppendLine($"        if (__pred_{method.MethodName} != null)");
                sb.AppendLine($"            query = query.Where(__pred_{method.MethodName});");
                sb.AppendLine();
            }
        }

        sb.AppendLine("        return query;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void GenerateSimpleCondition(StringBuilder sb, FilterFieldDefinition field)
    {
        var nullCheck = BuildNullCheck(field);
        sb.AppendLine($"        if ({nullCheck})");

        var left = field.EntityPath.StartsWith("e.") ? field.EntityPath : $"e.{field.EntityPath}";
        var right = $"filter.{field.PropertyName}" +
                    (field.IsNullableValueType ? ".Value" : "");

        // Всегда оборачиваем в скобки, чтобы тернарные выражения и цепочки вызовов
        // корректно работали с операторами сравнения (==, != и т.д.)
        left = $"({left})";

        var op = field.Operator switch
        {
            CompareOperator.Equal => "==",
            CompareOperator.NotEqual => "!=",
            CompareOperator.GreaterThan => ">",
            CompareOperator.GreaterThanOrEqual => ">=",
            CompareOperator.LessThan => "<",
            CompareOperator.LessThanOrEqual => "<=",
            _ => null // Contains, StartsWith, EndsWith — особые
        };

        string predicate;
        if (op is not null)
        {
            predicate = $"{left} {op} {right}";
        }
        else
        {
            var methodName = field.Operator switch
            {
                CompareOperator.Contains => "Contains",
                CompareOperator.StartsWith => "StartsWith",
                CompareOperator.EndsWith => "EndsWith",
                _ => "Contains"
            };
            predicate = $"{left}.{methodName}({right})";
        }

        // Null-guard
        if (field.NavigationNullGuard is not null) predicate = $"({field.NavigationNullGuard} && {predicate})";

        sb.AppendLine($"            query = query.Where(e => {predicate});");
        sb.AppendLine();
    }

    private static void GenerateSearchCondition(StringBuilder sb, FilterFieldDefinition field)
    {
        sb.AppendLine($"        if (!string.IsNullOrWhiteSpace(filter.{field.PropertyName}))");
        sb.AppendLine("        {");

        // Разбираем пути: "Description|Customer.Name|Customer.Email"
        var paths = field.EntityPath.Split('|');
        var conditions = new List<string>();

        foreach (var path in paths)
        {
            var guard = BuildNullGuard(path);
            var cond = $"e.{path}.Contains(filter.{field.PropertyName})";

            if (guard is not null)
                cond = $"({guard} && {cond})";

            conditions.Add(cond);
        }

        sb.AppendLine("            query = query.Where(e =>");
        sb.AppendLine($"                {string.Join(" ||\n                ", conditions)});");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static string BuildNullCheck(FilterFieldDefinition field)
    {
        return field.PropertyTypeCs switch
        {
            "string?" => $"!string.IsNullOrWhiteSpace(filter.{field.PropertyName})",
            var t when t.EndsWith("?") => $"filter.{field.PropertyName}.HasValue",
            _ => $"filter.{field.PropertyName} != null"
        };
    }
}